export const categories = [
  "Technology",
  "Programming",
  "Web Development",
  "Mobile Development",
  "AI & Machine Learning",
  "Data Science",
  "Cloud Computing",
  "DevOps",
  "Gaming",
  "Tutorials",
  "Productivity",
  "Startups",
  "Design",
  "UI/UX",
  "Cybersecurity",
  "Health & Fitness",
  "Travel",
  "Lifestyle",
  "Education",
  "Finance",
];
